### ISSUE TITLE
React Fondamentaux - QCM2 - question 2

### ISSUE THREAD

**Issue by nadlgit** [MikeCodeur/react-fondamentaux#4]
Il me semble que la réponse à la question 2 du QCM2 "Quel est l'équivalent de rootElement.append(element)" devrait être "ReactDOM.render(element, rootElement)"

**Comment by MikeCodeur** [comment]
Merci, cela est corrigé dans cette PR
https://github.com/MikeCodeur/react-fondamentaux/commit/4208e829e1a89c64d10cda015f07484b09b89524
